spring:
  application:
    name: shop-app
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # show SQL queries in the console
    hibernate:
      ddl-auto: none # prevent Hibernate from creating or updating the database schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8
        format_sql: true
server:
  port: 8088
api:
  prefix: /api/v1